### PR TITLE
Test/streetcode fact get all

### PR DESCRIPTION
**Pull request by yaninavoda**
## Summary of issue

Add unit tests for Streetcode/Fact GetAllFactsHandler

## Summary of change

Write tests for positive and negative scenarios

### CODE REVIEW

**Comment by HlibBondarev** [comment]
Place file GetAllFactsTest.cs to folder - MediatRTests/Streetcode/Fact

**Review by HlibBondarev — COMMENTED** [review]
Place file GetAllFactsTest.cs to folder - MediatRTests/Streetcode/Fact

**Review by OlhaPivniuk — COMMENTED** [review]
Change path StreetCode/Fact

**Review by HlibBondarev — APPROVED** [review]
Ok

**Review by vladtymo — APPROVED** [review]

**Pull request merged**
